# Generated by Django 5.1.2 on 2024-11-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=30),
        ),
    ]
